services:
  nginx:
    restart: always
    volumes:
      - ./nginx/templates-prod/default.conf.template:/etc/nginx/templates/default.conf.template:ro

  app1:
    restart: always

  app2:
    restart: always

  api:
    restart: always
