{
 "title": "Nginx Lab",
 "tags": [
  "nginx",
  "docker"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "active" },
    { "expr": "nginx_connections_reading", "legendFormat": "reading" },
    { "expr": "nginx_connections_writing", "legendFormat": "writing" },
    { "expr": "nginx_connections_waiting", "legendFormat": "waiting" }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "requests"
    }
   ]
  }
 ]
}